include:
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - /vendor
  - readme.md
  - CNAME

safe: true

#plugins:
#  - jekyll-redirect-from
#whitelist:
#  - jekyll-redirect-from

collections:
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      type: "pages"
    values:
      layout: "page"
