title: grin.io
author:
  name:  Alex Grintsvayg
  email: a@grin.io
production_url: https://grin.io
timezone: "America/New_York"
logo: /img/wizard-hat-social.png
twitter:
  username: grin_io
  card: summary

include:
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - /vendor
  - readme.md
  - CNAME

safe: true

permalink: /:title

plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
#whitelist:
#  - jekyll-redirect-from

collections:
  pages:
    output: true
    permalink: /:name

defaults:
  - scope:
      type: "pages"
    values:
      layout: "page"
  - scope:
      type: "posts"
    values:
      layout: "post"
      priority: 99999
      show_subscribe: true
  # for seo
  - scope:
      path: ""
    values:
      image: /img/wizard-hat-social.png
